import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, ShieldAlert, CheckCircle, Clock, ChevronLeft } from 'lucide-react';
import { SITE_CONFIG } from '../config/site';

export const TermsPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16 space-y-8">
      <div>
        <Link
          to="/"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-zinc-400 hover:text-cyan-400 transition-colors mb-4"
        >
          <ChevronLeft className="w-4 h-4" />
          <span>Back to Home</span>
        </Link>
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-zinc-900 border border-purple-500/30 text-xs font-bold uppercase tracking-widest text-cyan-400 mb-2">
          <FileText className="w-3.5 h-3.5" />
          <span>Legal Agreement</span>
        </div>
        <h1 className="text-3xl sm:text-4xl font-black text-white font-display uppercase tracking-tight">
          Terms of Service
        </h1>
        <p className="text-xs sm:text-sm text-zinc-400 mt-1">
          Effective date: September 2026 • Please read carefully before purchasing.
        </p>
      </div>

      <div className="bg-zinc-900/80 border border-zinc-800 rounded-3xl p-6 sm:p-10 space-y-6 text-sm text-zinc-300 leading-relaxed backdrop-blur-md">
        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">1. Acceptance of Terms</h2>
          <p>
            By accessing or purchasing top-up services from <strong>NEXORA</strong>, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you must refrain from placing orders on this platform.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">2. Customer Accuracy & Player ID Responsibility</h2>
          <p>
            Customers bear full responsibility for supplying correct in-game identifiers (UID, Character ID, Server ID, or Zone ID). 
          </p>
          <div className="p-4 bg-amber-950/30 border border-amber-500/30 rounded-2xl text-xs text-amber-200">
            <strong>Notice:</strong> Because digital gaming credits are credited immediately and irrevocably to the UID specified at checkout, NEXORA cannot reverse, retrieve, or re-route top-ups delivered to an incorrect Player ID provided by the customer. Always double-check your UID prior to order submission.
          </div>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">3. Manual Payment & Verification Process</h2>
          <p>
            All purchases currently operate under a manual mobile wallet verification system:
          </p>
          <ul className="list-disc pl-5 space-y-1 text-zinc-400">
            <li>You must transfer the exact payable amount using <strong>bKash</strong> or <strong>Nagad</strong> Send Money to our official number.</li>
            <li>You must submit the legitimate Transaction ID (TrxID) generated by your mobile provider.</li>
            <li>Verification is performed manually by our operators. Standard fulfillment takes between 1 to 5 minutes, although maintenance or network downtime on bKash/Nagad gateways may occasionally cause minor delays.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">4. Fraud Prevention & Zero Tolerance</h2>
          <p>
            Submitting fake, manipulated, already-used, or unauthorized Transaction IDs will result in permanent blacklisting of your mobile number and Player UID, along with reporting to relevant telecommunication authorities in Bangladesh.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-lg font-bold text-white">5. Governing Law</h2>
          <p>
            These terms are governed by the laws and digital commerce regulations of Bangladesh. Any disputes shall be subject to the exclusive jurisdiction of the courts of Dhaka, Bangladesh.
          </p>
        </section>
      </div>
    </div>
  );
};
